# My last option

I'd imagine that most people have some sort of a plan before they enter
university. It doesn't have to be an elaborate plan; it could be as
straightforward as "when I finish my undergraduate degree, I want to work for a
company and work my way up from there!" I had no plan. Picking what degree to
enrol in consisted of my mum and I looking through the course catalogue and
picking something that was not business-related. In her mind, a business degree
is useless because having started her own successful fast food business, she
believes that doing business is just common sense. We decided on a Bachelor of
Science degree, just because. And we never seriously considered what I was
going to do after I graduated. You may be reading this and thinking what kind
of a person spends a fortune paying for university (barely affording it)
without considering the potential upsides? Well, have you ever read about some
scam and found asking yourself who would ever fall for such a scheme? It's
always the people who don't know any better.

I got into university as a first-generation student and I didn't do very well
but I managed to graduate. I don't want to make up excuses for my mediocre
grades, so I'll just say it was because I didn't work very hard, which is true.
My mediocre grades and complete lack of confidence was a problem when it came
to finding a lab for an [honours
degree](https://en.wikipedia.org/wiki/Honours_degree#Australia). To those not
familiar with the undergraduate system in Australia (and don't want to read the
Wikipedia article I linked), an honours degree is a one year (in practice, it's
about ten months) undergraduate research program you can take after your
Bachelor's degree and has nothing to do with the traditional meaning of the
word "honours". You can consider it as a shortened Master's degree and if you
do well enough, you can actually commence a PhD, which is what a lot of people
do. I wanted to do a honours degree because it provides some practical
experience, which would help me find a job, and it would also potentially
qualify me to enter a PhD program.

I majored in biochemistry and microbiology for my Bachelor of Science degree. I
emailed a handful of professors in the school of biochemistry in total. The
first two said that they couldn't accommodate additional students. The next
asked for my grades and told me their lab only accepted students with a GPA of
6.5 or higher (7 is the highest), so that was a no. I managed to get a meeting
with the next professor but he wasn't impressed with my grades, especially the
grade I got for his class. I had one last meeting and it was with a
bioinformatics lab working on phylogenetics. It was my last shot.

I still remember the meeting I had with Mark and Rob (Mark's new postdoc). Out
of all my subjects, the best grade I got was for a course called Genomics and
Bioinformatics (BIOL3004). I didn't work especially harder for this subject so
perhaps it was a sign that that's where my skills are at. I milked it for all
it was worth to Mark and Rob since the rest of my grades were rubbish. They
worked on microbial phylogenetics, so I also mentioned my microbiology major.
In the end, it all came down to a single question. Mark asked Rob whether he
had the time to supervise me because he didn't. I stared at Rob. And he
casually said "Yeah".

## Second wind

I remember saying to myself at the start of honours that I've been granted a
second chance to prove myself and I would therefore make the most out of it by
working really really hard and getting a 1st class honours. Then I could only
show people my honours grade, which would effectively bypass my abysmal grades.
That was wishful thinking.

I literally jumped into the deep end of bioinformatics. In my Bachelor of
Science degree, I did not take a single computing or mathematics course and I
had no prior programming exposure (apart from writing some HTML, which doesn't
count). Despite being determined to work hard, it was difficult and almost
impossible for me to learn because what was supposed to be [introductory
material](https://www.goodreads.com/book/show/1209618.Inferring_Phylogenies)
was completely incomprehensible. I recall joining the first lab meeting where
they were discussing about these things called [Markov
clusters](https://davetang.org/muse/2014/01/23/markov-clustering/), which even
when I considered as separate words, had no idea what they were. But the thing
that was the major problem was that I didn't ask for help because first I
didn't want to bother anyone and second I didn't have the self confidence to
admit that I didn't know something.

It's easy to lose focus and determination when nothing you read makes any
sense. I tried coming into the lab on the weekends to read papers but I
couldn't make any sense of them. The only thing that kept my attention was
learning Unix and Perl because it was hands on and I was good at hacking (not
the type of hacking where you break into computer systems by exploiting
weaknesses but the type where you use something in a way that it wasn't
designed for) and Perl was (unfortunately) perfect for that. Back then you
couldn't look up Stack Overflow so you just kept trying stuff. Maybe if I
didn't use Perl, I wouldn't have gotten anything done in my honours year.
