# Prologue {-}

In the final year of primary school we had to write a short sentence describing what we wanted to be in the future for the yearbook. I remember this task well because I was stumped; I had no idea because I never thought about what I wanted to be or what I could be. Naturally, I looked at what my classmates and friends had written. I recall that my best friend wrote "doctor" and indeed he eventually became a medical doctor. He was easily the smartest kid in school, so no one had any doubt that he wouldn't become a doctor. I had always envied the fact that his mum was a teacher (although I probably wouldn't have enjoyed being him in his strict family). A lot of kids wrote that they wanted to "follow in my father's footsteps" and at that time I had no idea what that meant because I had never heard of the phrase before; I thought that they wanted to literally follow their father when they walked together and I thought that was a silly thing to write. I also recall that a few of my friends wanted to be a millionaire or be rich. While I agreed at that time that being rich would be nice, especially since my family was quite poor, it didn't cross my mind. Eventually after some thought I wrote "to live to 99 years old" because I thought it was funny. A nice kid named Ralph saw what I had written and told me that he would visit me the day before my 100th birthday to murder me because he didn't want me to unfulfill my dream. Mrs. O'Sullivan (my favourite teacher) was playfully shocked and I told Ralph that I looked forward to seeing him then.
