# Redemption

> 09/08/2006
> 
> Subject: CSIRO Work experience program
> 
> Dear Dr. Dalrymple,
> 
> My name is Dave Tang, a Bachelor of Science graduate currently without a
> science job. I've had difficulty looking for work as a scientist after my
> brief work at The University of Queensland ceased, partly because I'm stuck
> in the middle of two fields. I finished my Bachelor of Science degree with
> majors in microbiology and biochemistry and I've completed an honours degree
> in bioinformatics. However, I don't have the programming/mathematical
> background to strongly state that I am a bioinformatian nor enough
> laboratory experience to call myself a laboratory scientist and this has
> been a problem.
> 
> Naturally I searched CSIRO to see if there were any positions available.
> Though there was nothing suitable, I was happy to see that there is a work
> experience program for people with little or no work experience. I believe
> my interest lies more into bioinformatics and thus I would like to get more
> experience in this area. Your details came up as one of the principal
> investigators in bioinformatics at CSIRO.
> 
> I entered bioinformatics with minimal knowledge about the field and didn't
> have any programming knowledge. It was required for my research project to
> know a little bit of programming and I managed to learn some Perl and UNIX. 
> My research project was involved with detecting lateral gene transfer events
> among a group of bacteria. I've had some experience working with genomes and
> looking for SNPs, although not to the magnitude of eukaryotic genomes.
> 
> It would be one of the biggest joys to be able to gain some work experience
> in your lab. I am really sincere about honing my skills in this area and
> this would be a tremendous opportunity. I have included my CV and in it two
> referees, although your time and availability would be deciding factors, I
> kindly ask if you could consider my application. I thank you for your time
> and look forward to hearing your reply.
> 
> Sincerely,
> 
> Dave Tang

It is no exaggeration that the email above changed my life. It was a honest and
desperate plea after being unsuccessful in all of my job applications. At that
time there were no open positions for any bioinformatics roles. The only
available positions I could find that were kind of science related were the
following:

* Master Foods Graduate Program
* Junior Microbiologist
* Soil Technician
* Laboratory Assistant
* Research Assistant
* Bioprocessing Assistant
* Scientist
* Amcor Australasia Graduate Program
* Australian Communications and Media Authority Graduate Program
* Department of Agriculture, Fisheries and Forestry Graduate Development Programme

I have a folder on my Hotmail account called "Rejected work", that holds all
the rejection emails I received from applying to the positions above.

When Brian replied my email saying that he was interested and wanted to talk
about possibilities, it was one of the happiest days of my life. I didn't even
care that they didn't pay me. But of course I had to work 9-to-5 on Saturday
and Sunday to make ends meet. I kept this up for five months, the duration of
my work experience programme.

## Wes

When I was at CSIRO I was under the tutelage^[I learned the word "tutelage" from Brian and I had never seen it until I read a document written by him. To use it here is extra special to me.] of Wes, who was the sys admin and bioinformatician for Brian's group. I was a bit nervous when I first met Wes because he had a stern demeanour. The first thing he asked me to do was to write a Perl script to convert one file format to another. I went back to my office, wrote it quickly, and returned to show him what I had done. He was impressed and said he had to come up with more difficult tasks for me to do. And that's how we worked during most of my "internship": he would assign me a task and I'll write a Perl script that would complete the task. But the thing that was the most beneficial was that he would take the time to go through my code line by line with me and suggest how he would tackle the problem. He never told me that his way was the right or better way, only that it was how he would do it but I always did it his way because it was better. And this was how I gradually got better and better in Perl, which at that time was what a lot of people used for bioinformatics.

I was extremely motivated and diligent during my work experience because once again I felt like I was given another chance; I had to make the most out of it. However when my time was almost up, it wasn't clear whether they had funding for me and I was getting tired of working two jobs mostly because I couldn't play basketball with my friends/team. I actually didn't want to expect anything because I didn't want to be disappointed. But when Brian told me they had funding for me for at least a year, I was ecstatic! I was going to make a living as a scientist! I remember telling Wes that they had hired me and he said with a smile: "What!? Against all my recommendations!"

I'm forever grateful to Brian and Wes because they gave me the confidence to become a bioinformatian. I'm getting ahead of myself but when my time was up at CSIRO and I managed to get a new job as a bioinformatian at The University of Queensland (UQ), I wrote a long email thanking Wes. I still remember his reply although I can't find a copy of his email. He told me that he was happy to have been my mentor and that sadly not that many people have the enterprise to learn even though he was always willing to teach. He made me feel like giving myself a little bit of credit. And that was the last thing and maybe the most important thing he bestowed on me.
