--- 
title: "The Bioinformatics Journey"
author: "Dave Tang"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output:
  bookdown::gitbook:
    lib_dir: assets
    split_by: section
    config:
      toolbar:
        position: static
---

# Preface {-}

> "How vain it is to sit down to write when you have not stood up to live."
>
> --- Henry David Thoreau

I have always wanted to write a book. Several things have stopped me, one of
which is the pure vanity of the endeavour. Another reason is that I am a poor
writer. But probably the main reason was that I simply lacked the discipline
required for writing a book, decent or otherwise. Believe it or not, I have
actually been asked twice to write a book. The first time was to write a book on
machine learning, which I felt (and still feel) inadequate writing. The second
time was to write a book on R and bioinformatics, which I actually agreed on
writing. However while preparing the structure of the book, I realised that a
lot of what I wanted to write about is already freely available. So I dropped
the project and decided then that anything I will write in the future will be
freely available.

Have I finally gained enough self-discipline to write a book? I guess we will
see!

Finally, the title is simply a substitution of the word Dangerous with
Bioinformatics from the book [The Dangerous
Journey](https://www.goodreads.com/book/show/7967538-the-dangerous-journey) by
Tove Jansson. It's a children's book about a little girl who enters an exciting
world full of wacky, wild, and weird things. Kinda like bioinformatics.

## Why this book {-}

I'd like to share my story of how I ended up working in bioinformatics in the
hopes that it will be useful to those who are planning on starting a career in
bioinformatics (or in some other area of work). I come from a low-income family
and was the first in my family to have attended university. On top of this, I
grew up in an isolated and exotic island, called Papua New Guinea, in a highly
dysfunctional family. I learned most of life's most important lessons the hard
way and if I can prevent at least one person from making the same mistakes that
I have, I'd consider this book a success.

One of my biggest problem in life is not seeking help when I need it because
it's not something I learned to do. This is one reason why I have mostly
learned things the hard way. There is value in this but it's a major impedance
in terms of time because it not only stops you from achieving what you want but
it also takes time to bounce back mentally. To the old adage of what doesn't
kill you only makes you stronger, which is attributed to Friedrich Nietzsche,
you may become stronger but it can also leave you disheartened.

I also like to write because it gives me an opportunity to self-reflect. I
think it's important to evaluate your current situtation from time to time.
Therefore, even if no one reads this apart from myself, it will have served one
purpose. Now, I will probably read what I've written in the future and cringe.
If I'm lucky enough to get someone else reading this, they may read this today
and cringe. I think I'm fine with that because what I write reflects who I am
right now. I may outgrow these opinions in the future and that's part of
learning and moving on. It's like looking back at code you've written many
years ago and being in disbelief at how bad it is. But this is an indication
that you've improved!

## Structure {-}

I have tentatively structured the book based on different positions I have held,
starting from an Honours student to my current position.
